baseURL = "https://ammarasmro.github.io/"
languageCode = "en-us"
title = "Ammar Asmro"
theme = "creative"

# Enable comments by entering your Disqus shortname
disqusShortname = "ammarasmro"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-114411937-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "This is my first website. I built it to show my portfolio and practice web development."
  copyright = "&copy;2018 Ammar Asmro"
  sidebarAbout = [
    "I am a software engineer with passion to build solutions. Searching for opportunities to take on challenges and solve real world problems",
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "ammarasmaro@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Blog"
  url = "blog/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/amoryasmaro"
  googleplus    = "https://plus.google.com/+AmmarAsmaro"
  email         = "ammarasmaro@gmail.com"
  twitter       = "https://twitter.com/ammarasmaro"
  linkedin      = "https://www.linkedin.com/in/ammar-asmro/"
  stackoverflow = "https://stackoverflow.com/users/7568128/ammar-asmaro"
  instagram     = "https://www.instagram.com/amoryasmaro/?hl=en"
  github        = "https://github.com/ammarasmro"
